version: "3.8"
services:
  websocket: 
    build: 
      context: .
      target: base
    network_mode: "host"
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    stdin_open: true
    tty: true
